### ISSUE TITLE
use == instead of instanceof in for loops

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-compiler#1968]
In my tests, it appears that:

            Object x;
            final Finished fin = finished_.get_();
            while ((x = iter.next())!=fin) {
                X next = (X) x;
            }

Is a little faster than:

            Object x;
            while (!((x = iter.next()) instanceof Finished)) {
                IntegerHolder next = (IntegerHolder) ih;
            }

**Comment by tombentley** [comment]
I've just benchmarked `instanceof` with two alternatives. In the first I declare a local `fin` outside the loop (as above) and use `!=` in the loop condition. In the second I just invoke `finished_.get_()` each time the loop is tested.

On my desktop machine (other desktop stuff running) I ran each variation ten times with a Java 7 Hotspot in `-server` mode . For me, on average, `instanceof` performed best, then the version doing the method call each time, and the version using a local variable did worst. But we're talking very small differences (1.5%).

Then I ran the benchmark with the JVM in interpreted mode (but only run once rather than ten times because it ran about 20-30 times slower). In this case the version with `!=` and a local variable outside the loop ran faster (about 20% faster than `instanceof`), then the `instanceof` and finally the `!=` without local variable version (about 15% slower than `instanceof`).

My problem with this change though is that our loops are getting more and more bloated. Since the JIT won't inline code which is larger than a certain threshold, the consequence of such bloat is to make programs slower.

So I'm not convinced this is really worth doing in its present form, but I'm interested in what @FroMage and @quintesse might have to say.

**Comment by quintesse** [comment]
Well seeing you did quite a bit of testing I'd say we leave it like this for now. That it runs slower when unJITted doesn't seem like a good enough reason to make this change.

**Comment by gavinking** [comment]
I also did quite a bit of testing, and I saw different results on Mac.

**Comment by tombentley** [comment]
@gavinking do you remember (or can you find out) how *much* faster `!=` was for you?

**Comment by gavinking** [comment]
It was not a huge difference.

**Comment by FroMage** [comment]
So let's close this then?

**Comment by FroMage** [comment]
Closing.
