### ISSUE TITLE
compiler should direct verbose output to passed PrintWriter

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-compiler#1969]
I have added a setting to the IDE to direct verbose output to the console. It doesn't work, because apparently verbose output is just sent straight to `System.out` instead of to the given `PrintWriter`.

**Comment by FroMage** [comment]
So I think it's a combination of two things: the first is that I guess your code is wrong because you probably pass a `null` `Writer` to the `CeyloncFileManager` you create, which sets a `Writer` in the `Context`, and then when you call `compiler.getTask(...)` with this `CeyloncFileManager` you pass a `Writer` but because one was set in `CeyloncFileManager` yours is ignored. You need to pass it to the `CeyloncFileManager`. Yeah I know the API stinks, but that's a javac API we never got around to providing an alternative for.

I will try to fix the IDE code for you.

The other thing is that we were logging to stderr at a couple places by mistake.

**Comment by FroMage** [comment]
OK, so you were using it correctly and it now works, except that to enable verbose mode for everything you should set `--verbose`, and for just `code` you should set `--verbose:code`. In your UI you can only set `--verbose:XX` and currently there's no value of `XX` that is equivalent to `--verbose` so you can only log specific things.

I will add `--verbose:all` as an alias of `--verbose`, but no idea how it works on JS, @chochos ?

**Comment by chochos** [comment]
I think @quintesse fixed it to work the same as in JVM.

**Comment by chochos** [comment]
But I need to review where I check those verbose flags to make sure that output is only done when the proper flag is set.

**Comment by FroMage** [comment]
OK done. Note that I don't get any verbose output from JS with `--verbose:all` ATM. I do get "Created module default" from it, but that's all.

**Comment by FroMage** [comment]
Closing, feel free to reopen an issue on `ceylon-js` @chochos if required. I don't know what `--verbose:all` is supposed to log on JS.

**Comment by chochos** [comment]
Well I guess it should spit out the AST and the generated code, just like the JVM compiler does.

**Comment by chochos** [comment]
What are other valid options besides `all` and `code`?

**Comment by chochos** [comment]
Nevermind, found them with `ceylon help compile`

**Comment by chochos** [comment]
I'm using `logger.debug` to output all that stuff, maybe that's why you don't see it? Should I use `info` instead?

**Comment by FroMage** [comment]
No idea. I use the given `PrintWriter`.

**Comment by FroMage** [comment]
Does the IDE give you that logger instance?

**Comment by chochos** [comment]
I'm testing on CLI, no idea if the IDE gives the compiler a logger

**Comment by FroMage** [comment]
And on the CLI do you get the verbose output?

**Comment by chochos** [comment]
The `Options` object has an `outWriter` property, I'll check if the IDE uses that

**Comment by FroMage** [comment]
I just made it use that

**Comment by FroMage** [comment]
So yes it does, but still I see nothing.

**Comment by gavinking** [comment]
Thanks.

**Comment by chochos** [comment]
Just pushed some changes to use that writer.
