### ISSUE TITLE
Optimize iteration of Array<Integer>, Array<Float>, etc to eliminate boxing

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-compiler#1976]
@tombentley it seems to me that we could add `unsafeLongItem()`, `unsafeDoubleItem()`, `unsafeBooleanItem()`, and `unsafeStringItem()` to `Array` and use those when iterating the `Array` using a `for` loop, thus eliminating the boxing that occurs.

WDYT?

**Comment by tombentley** [comment]
@gavinking we already avoid the boxing overhead when iterating over a compile time `Array<Integer>`, `Array<Double>` etc. 

    void arrayOfIntegers(Array<Integer> array) {
        for (element in array) {
            print(element + 5);
        }
    }

transforms to 

    private final void arrayOfIntegers$priv$(final .ceylon.language.Array<.ceylon.language.Integer> array) {
        final .java.lang.Object array$0 = array.toArray();
        final int length$1 = .com.redhat.ceylon.compiler.java.Util.arrayLength(array$0);
        loop_0: for (int i$2 = 0; i$2 < length$1; i$2++) {
            final long element = .com.redhat.ceylon.compiler.java.Util.getIntegerArray(array$0, i$2);
            .ceylon.language.print_.print(.ceylon.language.Integer.instance(element + 5L));
        }
    }

It's possible that the JVM would be able to better optimize the code if we did a similar thing using `unsafeXxxItem()`, rather than the `Util` calls.

It also seems we don't do it for `Array<String>`.

**Comment by tombentley** [comment]
There are lies, damn lies and microbenchmarks. The ones I just did showed no meaningful difference between what we generate now and either instance or static `unsafeXxxxItem()` methods.
