### ISSUE TITLE
Constructor + comprehension + switch/else expression exposes java.lang.String

### ISSUE THREAD

**Issue by jpragey** [ceylon/ceylon-compiler#1984]
Compiling:
``` ceylon
class A {
	String[] elements;
	shared new A() {
		this.elements = [for(e in [""])
			switch(e)
			case ("") ""
			else e
		
		];
	}
}
```
prints:
```
> ceylon compile
source/org/app2/run.ceylon:9: error: incompatible types
			else e
			     ^
  required: java.lang.String
  found:    ceylon.language.String
1 error
Note: Created module org.app2/1.0.0
ceylon compile: There was 1 error
```

**Comment by tombentley** [comment]
I don't think constructors are really part of this problem here as a class with a method

    shared void m() {
        value elements = [for(e in [""])
        switch(e)
        case ("") ""
        else e
        
        ];
    }

also has the problem. I'll let whoever did switch/else expressions pick this one up.

**Comment by tombentley** [comment]
What I think is happening here is:

* the synthetic `Variable` for the `switch(e)` is being marked as unboxed,
* however we don't actually generate Java variable in this case, so there's no (unboxed) substitution
* so we generate code where (effectively) the original declaration of `e` is visible, and because that's in a comprehension that's boxed
* so when we get to transform the expression `else e` we think the expression `e` is already unboxed (because it's declaration is unboxed), but we're wrong (because we didn't generate an unboxed substitution).

I suppose the simplest fix would be to generate an unboxed substituted variable for the `switch` if the synthetic `Variable`'s declaration has different boxing/erasure etc than it's original declaration.
