### ISSUE TITLE
Incompatible type of nothing in switch expression with object cases

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-compiler#2001]
```ceylon
shared void run() {
    value c = switch (0) case (0) smaller case (1) equal else nothing;
}
```
> source/tmp/run.ceylon:2: error: incompatible types
```ceylon
    value c = switch (0) case (0) smaller case (1) equal else nothing;
                                                              ^
```
  required: Comparison
  found:    Object

The error disappears if both cases evaluate to the same object (e. g. `case (1) smaller`); in that case, the compiler casts `nothing` to `smaller_`.

As always, [generated code](https://gist.github.com/lucaswerkmeister/6b22840f82126e9d9ca5), `@noanno`’ed.

**Comment by tombentley** [comment]
The problem here was that the type of the switch is these days `smaller|equal` (as a result of https://github.com/ceylon/ceylon-spec/issues/865) so I suppose I need to add a `denoteableType()` call somewhere. 

My concern is that `denoteableType()` is going to see liberal use through the code generator as we see more of this sort of bug. I don't know whether there's a right or a wrong place to call `denoteableType()`, because aren't we supposed to reify types like `smaller|equal` ?

**Comment by gavinking** [comment]
We only reify them when they are type args, and according to the spec such types are never inferred.

**Comment by tombentley** [comment]
> We only reify them when they are type args

Right. So when constructing a reified type argument I need to ensure I'm not using a `denotableType()`-ed type. But otherwise I can use `denotableType()` freely.

> according to the spec such types are never inferred.

So does that mean this bug is a typechecker bug?

**Comment by gavinking** [comment]
@tombentley read again what I just wrote :)

**Comment by gavinking** [comment]
Hint: there are no type args in the above code!

**Comment by tombentley** [comment]
I assume that means it's not a typechecker bug, and we can expect to find this `foo|bar` stuff everywhere except for stuff like `value` and implicit values like `for` variables.

**Comment by gavinking** [comment]
No, it's not a bug, and yes, the backend needs to be able to accommodate expressions with types like this.
