### ISSUE TITLE
"Inherited member is refined by intervening superclass" that isn't "intervening"

### ISSUE THREAD

**Issue by kingjon3377** [ceylon/ceylon-compiler#2011]
Fairly often, when trying to create a subclass of a class in the Java SDK (such as the following MWE), I get a compilation error that doesn't make sense.

```ceylon
import javax.swing.tree {
	DefaultMutableTreeNode,
	MutableTreeNode
}
class MWETreeNode() extends DefaultMutableTreeNode() {
	// error: inherited member is refined by intervening superclass: 'DefaultMutableTreeNode' refines 'remove' declared by 'DefaultMutableTreeNode'
	shared actual void remove(Integer int) => super.remove(int);
	// error: inherited member is refined by intervening superclass: 'DefaultMutableTreeNode' refines 'remove' declared by 'DefaultMutableTreeNode'
	shared actual void remove(MutableTreeNode? mutableTreeNode) =>
		super.remove(mutableTreeNode);
	shared actual void setUserObject(Object? obj) {}
}
```

**Comment by tombentley** [comment]
@gavinking I'm not quite sure what's going on here, because I'm not really sure what case that error message is intended to cope with. However it looks like the logic in `ExpressionVisitor.checkSuperInvocation()` doesn't cope properly with abstraction methods. `etm` is the abstraction method in this case.

**Comment by jvasileff** [comment]
Ah, I actually ran into this before too, but didn't follow up. I think it can be generalized to "an attempt to call `super.foo(X)` from a Ceylon subclass where `foo` is overloaded in the superclass."

What I came up with as a theory was:

* Ceylon likes to verify the provenance of all methods, not just their signatures. For example, you can't extend a class that implements `foo(X)` and also satisfy an interface that requires `foo(X)` unless the class also satisfies that interface.
* `super.foo(X)` requires the target `foo(X)` to be of the same provenance (and be disambiguated when necessary, but I believe that point is tangential)
* there is an interop bug relating to the tracking the provenance of overloaded methods. So, the type checker is unaware that `foo(X)` is actually the same `foo(X)` that the calling class assumes.

**Comment by tombentley** [comment]
@gavinking I think this is a typechecker bug, unless you can persuade me the loaded model is wrong, somehow.

**Comment by gavinking** [comment]
@tombentley well according to @jvasileff's explanation, the suspicion seems to fall on the model loader, no?

**Comment by tombentley** [comment]
Well it's not clear to me @gavinking. From `ExpressionVisitor.checkSuperInvocation()`:

                    Declaration etm = ci.getExtendedTypeDeclaration()
                            .getMember(member.getName(), null, false);

It seems to me correct for `etm` to be the abstraction method, because there's no way given that API for it to return the right overloaded method, but then the condition:

    if (etm!=null && !etm.equals(member) && etm.refines(member)) {

doesn't take abstraction methods into account. 

Maybe it *is* the model loader that's wrong, but I'm afraid you'll have to tell me it's supposed to be.

**Comment by gavinking** [comment]
@tombentley you're right. It's fixed now.

**Comment by tombentley** [comment]
Thanks

**Comment by FroMage** [comment]
@tombentley there's a test file missing.

**Comment by FroMage** [comment]
@gavinking I think this change broke three compiler tests.

**Comment by FroMage** [comment]
Sorry @gavinking my bad, you just added new errors, that's fine.

**Comment by tombentley** [comment]
Add missing test fail. Closing
