### ISSUE TITLE
Ternary like construct with type checking

### ISSUE THREAD

**Issue by dhoehmann** [ceylon/ceylon-compiler#2025]
//This example compiles fine
	Object i = 100;
	
	if (is Integer i) {
		print(i+1);
	} else {
		print(0);
	}
	
	//The following three examples refuse to compile. Why?
	//Is it by intention or mistake?
	
	print (i is Integer then i+1 else 0);
	
	print (is Integer i then i+1 else 0);
	
	//I think I get this one: j could be modified within the if block and change its type
	variable Object j = 100;
	if (is Integer j) {
		print(j++);
	} else {
		print(0);
	}

**Comment by quintesse** [comment]
The two single print-statements are because we don't do type narrowing inside expressions (yet? I thought there was an issue on ceylon-spec for this. @gavinking ?).

The last example has to be rewritten otherwise we can't guarantee `is Integer` inside the block (you could assign a String to it for example). If you write it like this everything is okay

```ceylon
variable Object j = 100;
if (is Integer int=j) {
    print(int);
    j=int+1;
} else {
    print(0);
}
```

**Comment by dhoehmann** [comment]
Thanks for the quick response. I'd definitely vote for type narrowing inside expressions!

**Comment by quintesse** [comment]
Oh I think we all *want* it :)

**Comment by FroMage** [comment]
We do have inline if expressions in the upcoming release:

```ceylon
print (if (is Integer i) then i+1 else 0);
```

**Comment by quintesse** [comment]
Ah yes, forgot all about those!
