### ISSUE TITLE
Strange error for formal class in non-top-level interface

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-compiler#2032]
This code
```ceylon
shared void run() { // keep the method if you copy the example
    interface Foo{
        shared formal class Bar() {}  
    }  
} 
```
compiled
```
source\bar\run.ceylon:2: error: package Foo$impl does not exist
    interface Foo{
    ^
```

**Comment by tombentley** [comment]
The problem here is the `@Member` annotation mentions `Foo$impl.Bar.class`, but that's a class local to `run()`. @FroMage I'm not sure what the expected behaviour is here. I don't see how we can refer to that class (even if we do know how javac mangles its name, I don't think it will let us use it in a `.class` literal because it's compiler specific, right?)

**Comment by FroMage** [comment]
Damn, OK I'll take it.

**Comment by FroMage** [comment]
Fixed.

**Comment by tombentley** [comment]
Thanks
