### ISSUE TITLE
Error satisfying interface parameterized with union or intersection

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-compiler#2038]
in:

```ceylon
shared interface Foo<Element> {
    shared formal void run(List<Element> x, List<String> y);
}

shared class FooImpl() satisfies Foo<Identifiable&Usable> {
    shared actual void run(List<Identifiable&Usable> x, List<String> y) {}
}
```

out:

```
$ ceylonDev compile simple
error: FooImpl is not abstract and does not override abstract method run(List<? extends Object>,List<? extends String>) in Foo
source/simple/run.ceylon:6: error: name clash: run(List,List<? extends String>) in FooImpl and run(List<? extends Element>,List<? extends String>) in Foo have the same erasure, yet neither overrides the other
    shared actual void run(List<Identifiable&Usable> x, List<String> y) {}
           ^
  where Element is a type-variable:
    Element extends Object declared in interface Foo
2 errors
Note: Created module simple/1.0.0
ceylon compile: There were 2 errors
```

A theory is that the compiler decides to use an erased type for the first argument `x` due to the complex type, but doesn't do the same with the second argument `y`.

**Comment by quintesse** [comment]
What I changed seems to fix this and doesn't break any tests nor the SDK or whatever else I throw at it, but I have the feeling it's too simple a solution, code review by @FroMage or @tombentley would probably be a good idea.

**Comment by tombentley** [comment]
tbh I don't think that fix right. It obviously fixes this issue, but it there doesn't seem to be any rational basis for that change. The type is not being used as a type argument, so it shouldn't have that flag. and I don't really see that the emptiness of the parameter list is really important.

**Comment by quintesse** [comment]
Well the "rational" basis is that here we're talking about a type for a parameter that's part of a method that is implementing an interface method. So the type is not "free" to be whatever it wants, it needs to adhere to the type of the interface that already exists. And in this case only in the case of types that have type parameters.
Without that flag the type gets reduced to `List` instead of `List<? extends .java.lang.Object>`, no other flag seems to have the same result and I wasn't sure of using `JT_TYPE_ARGUMENT` was meant only for type arguments themselves or if it also meant "preserve all type arguments".

So I added a new flag `JT_REFINED` for this case where, like `JT_TYPE_ARGUMENT`, we need the full "unreduced" type but unlike that flag it doesn't imply `JT_NO_PRIMITIVES` so the test for type parameters could be removed.

Any better this way?

**Comment by tombentley** [comment]
> Without that flag the type gets reduced to List instead of List<? extends .java.lang.Object>

Do you understand why it decides to use `List` though? In particular, the problem is that the type in the `implements` clause is not raw, but we're then using a raw type in a member. I think understanding *that* inconsistency is the important thing, otherwise this is likely to pop up somewhere else in another guise.

**Comment by quintesse** [comment]
Sure, it's because the type has a union for a type argument, it's something like `List<Identifiable&Usable>` but overriding a `List<Element>`, so the latter gets transformed to `List<? extends Object>` and the former (without the flag) to `List`, which is okay if it wasn't overriding the type `List<Element>`.

**Comment by quintesse** [comment]
Maybe a better name for the flag would be `JT_NARROWED`? Because it's only used in the case of a narrowing refinement.

**Comment by tombentley** [comment]
So what you're saying it that when `makeJavaType()` is called using `JT_SATISFIES` we're generating List<Object>, fine I get that. What I want to understand is why we generate a raw `List` with *whatever the flags are without your patches* (you've not said). There must be some reason for going raw there, presumably based on some other test case (because we generally avoid raw types where we can).

**Comment by quintesse** [comment]
I have not mentioned `JT_SATISFIES`, we do this when *no* flags are passed, that's the default behaviour for types that have type arguments that are unions or intersections.

**Comment by quintesse** [comment]
The docs for `AbstractTransformer.rawSuperType()` state:

```
// For any other union type U|V (U nor V is Optional):
// - The Ceylon type Foo<U|V> results in the raw Java type Foo.
// For any other intersection type U&V:
// - The Ceylon type Foo<U&V> results in the raw Java type Foo.
```

**Comment by tombentley** [comment]
That's not really a reason, it's just some documentation someone once wrote. What I want to know is if we were to generate a non-raw type what then breaks, and why. And the answer seems to be very little breaks. So I'm still wondering why we're using raw types here.

**Comment by quintesse** [comment]
Well you know what they say about curiosity and cats ;)
