### ISSUE TITLE
missing line number info for iterable args in named arg list

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-compiler#2046]
Given:

```ceylon
shared void runme() {
    printAll { 1.0, 2.0 };
}
```

There is an inner subclass of `LazyIterable`. It's initializer doesn't seem to have line number info, so the debugger complains.

**Comment by tombentley** [comment]
The problem sees to be that the inner subclass gets no `LineNumberTable` attributes at all in the `.class` file, so Eclipse Debugger whinges. In fact there *ought* to be a `LineNumberTable` because the `Float` box instantions are attributed to the relevant line.

I can easily add a `LineNumberTable` by attributing the instantiation and the inner class code (including the `switch`) to line 2, but I suspect that's not what you're after @gavinking? Would you want to step into the instantiation of the `Iterable`?

**Comment by gavinking** [comment]
@tombentley I'm happy if it steps to line 2.

**Comment by tombentley** [comment]
@gavinking this should now be fixed.

**Comment by gavinking** [comment]
Excellent, thanks.
