### ISSUE TITLE
Javac errors when I switch order of satisfied interfaces in SDK

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-compiler#2048]
Changing

```ceylon
shared interface MutableList<Element>
        satisfies  List<Element> & ListMutator<Element> { ... }
```

Into:

```ceylon
shared interface MutableList<Element>
        satisfies  ListMutator<Element> & List<Element> { ... }
```

Causes these errors when compiling the `test.ceylon.collection` modules:

```
error: incompatible types
  required: Ranged<? super Integer,String,? extends List<? extends String>>
  found:    MutableList<String>
../ceylon-sdk/test-source/test/ceylon/collection/mutableList.ceylon:13: error: createList(Iterable<? extends String,? extends Object>) in MutableListTests clashes with createList(Iterable<? extends String,? extends Object>) in ListTests
    shared actual formal MutableList<String?> createList({String?*} strings);
                  ^
  return type MutableList<String> is not compatible with List<? extends String>
error: incompatible types
  required: Ranged<? super Integer,String,? extends List<? extends String>>
  found:    MutableList<String>
3 errors
```

I've checked the generated code and the tests compile to _exactly_ the same Java code, while the collection module changes a total of two casts, but no public method signature change at all, and of course the order of the implemented interfaces. So it's not likely we can fix these errors by changing the code we generate unfortunately.

**Comment by tombentley** [comment]
@quintesse could this be the same problem you had last week with the order of source affecting the outcome of the 'untrusted type' algorithm?

**Comment by quintesse** [comment]
You mean #2026 ? Perhaps, but the generated Java code is *slightly* different in that case (the untrusted type annotation), but perhaps @FroMage was comparing unannotated code in this case?
Anyway I didn't take a further look at #2026 because I'm not really sure on the best way to fix it.

**Comment by tombentley** [comment]
This is similar to #1240, in fact. Fixing javac's subtyping algo is not really an option, since we'd end up having to teach it the principle type algorithm (it finds supertype as the first interface and returns that, we could make it continue, but `Types.asSuper()` must return a single type, so we'd need to figure out the principle type of all the super types the visitor found...) basically that's not going to fly. 

So we'll have to do as @FroMage did in #1240 and attribute the `MethodSymbol` with `CEYLON_METHOD_OVERRIDE_CHECKED` some time before we worry about return type substitutability.

**Comment by tombentley** [comment]
Doing that only gets rid of the first error: When we attribute the method declaration we decide that the return type of the method is incompatible with its declared return type.

What I can do though is clobber `Types.isSubtypeUnchecked()` so that when we're compiling Ceylon we apply a looser check against the raw types instead of the generic types. That wouldn't have been sufficient to fix #1240 though, so I'm not really sure if it's the best thing to do here.

**Comment by tombentley** [comment]
That clobbering works and fixes this issue. But I wanted to think it through more before pushing. 

One concern I had was whether javac would still generate the right bridge methods when there's more than one instantiation of a superinterface. I've not been able to cause any problems there, and I assume it's something @FroMage dealt with then he first added support for inheriting multiple instantiations and it "just works". But all the same I wonder what @FroMage thinks about my proposed solution, or whether he can think of a better one.

**Comment by FroMage** [comment]
I agree with your proposal and I don't know at all if we breaked bridge methods or not. We haven't ever run into issues related to them until now.
