### ISSUE TITLE
`ceylon import-jar` does not recognize that the `java.awt.peer` package is part of the 'java.desktop' module

### ISSUE THREAD

**Issue by ncorai** [ceylon/ceylon-compiler#2080]
Ceylon 1.1.0, Windows 8.1, JDK 7.76 or 8.31 (makes no difference), 64 bit
Running `ceylon import-jar --descriptor=descriptors/activation-module.properties javax.activation/1.1.0 libs/activation.jar` using the following descriptor:
```
+java.base=7
+java.desktop=7
```
I see the following output:
```
Checking declared dependencies:
    shared java.base/7 ... [OK]
    shared java.desktop/7 ... [OK]
Modules containing the following packages need to be declared as shared imports:
(Tip: try running again with the '--show-suggestions' option)
    java.awt.peer
ceylon import-jar: Problems were found, aborting.
```
Notes:
* I know I could `--force` the outcome but the matching `ceylon-import-jar` Ant task does not offer that possibility AFAIK.
* Let's ignore the issue of whether I actually need `activation.jar` in java 7, unless it matters for the problem at hand.

**Comment by quintesse** [comment]
@ncorai Well actually the `java.awt.peer` class is not officially part of `java.desktop`, it's a "hidden" package.
But we don't force you to define JDK imports anymore in the latest version of the import tool because legacy JARs implicitly have access to the entire JDK anyway. (You can still define them if you want and the import tool will still tell you about them but other than that it will ignore any JDK modules).
So closing.

**Comment by quintesse** [comment]
I don't think I was being entirely clear. The fact that `java.awt.peer` is "hidden" (not officially part of the `java.desktop` module) still means that you'll need to use `--force`.
And in the latest code from master the ant task does supports a `force` attribute.
