### ISSUE TITLE
Optimized for loop & overflow

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-compiler#2130]
Neither of these produce output:

```ceylon
    void spanTest(Integer min) {
        variable value x=0;
        for (i in min..runtime.maxIntegerValue) {
            print(i);
            if (x++ > 2) {
                break;
            }
        }
    }
    spanTest(-2);
```
```ceylon
    void measureTest(Integer min) {
        variable value x=0;
        for (i in min:runtime.maxIntegerValue) {
            print(i);
            if (x++ > 2) {
                break;
            }
        }
    }
    measureTest(1);
```

This relates to ceylon/ceylon.language/issues/656.

**Comment by tombentley** [comment]
Fixed for iteration over measures. Spans next.

**Comment by tombentley** [comment]
Optimizing span iteration turns out to be much harder. Specifically getting a C-style `for` loop to behave the same as the iterator would boils down to replicating the same logic as `Span.iterator()` and `Span.By` for increment and loop exit conditions. An additional problem is `by()` special cases `step==1` and the overflow behaviour of `Span.iterator()` and `Span.By.iterator()` are different. This means that to generate correct code for `for (i in (start..end).by(step))` the loop condition and increment depend on the step. I'm effectively teaching the compiler how to inline all the code used for the iterator.

**Comment by gavinking** [comment]
@tombentley Well, yes, but the difference is you don't need to box the `long`s.

**Comment by tombentley** [comment]
Still a couple of edge cases to fix here, but I need to work on something else today.

**Comment by gavinking** [comment]
@tombentley good ;)

**Comment by jvasileff** [comment]
I'm guessing related to this work, I'm getting:

```ceylon
    print(3 in 0:3); //true
    print((0:3).contains(3)); //false
```

**Comment by tombentley** [comment]
I think this is fixed with the exception of those Span<Character> affected by https://github.com/ceylon/ceylon.language/issues/717, where the unoptimized loop never executes because the Span constructor throws, but the optimized loop is executing at least once. I suppose I can add a check for those cases, but I'll wait to see if people care about fixing https://github.com/ceylon/ceylon.language/issues/717 first.

**Comment by tombentley** [comment]
Add *immediately* after I made that comment I find something else which is broken.

**Comment by tombentley** [comment]
I have at this point concluded we're flogging a dead horse in trying to squeeze the span iteration optimization into a `for` loop, and that a `do`/`while` loop is the much more natural construct, though it will complicate the transformation of `continue` directives with the iterated block.

**Comment by tombentley** [comment]
Fixed, finally.
