### ISSUE TITLE
problem with initialization of unshared field via constructors.

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-compiler#2145]
This code:

```ceylon
class Hello {
    String who;
    shared new For(String who) {
        this.who = who;
    }
    shared new World()
            extends For("world") {}
    print("Hello " + who);
}
```

Results in:

```
Cannot find symbol
  symbol:   variable who
  location: class bug.Hello
```

**Comment by tombentley** [comment]
The problem here is that we need to consider `who` as captured (and thus reify it as a field, not a local variable in the constructor) and we're not getting that right. What's interesting is what exactly we consider "right" to be. With initializers the situation was pretty clear but with constructors we have a choice in some circumstances:

By analogy with initializers, we probably wouldn't decide `x` was captured in a class like this:

    class NotCaptured {
        Integer x
        new A() {
            this.x=1;
        }
    }

because `x` is only referred to in a single constructor there's no need to reify it as a field, doing so only leads to memory leaks.

So similarly we probably wouldn't consider this captured: 

    class NotCaptured2 {
        Integer x;
        new A() {
            this.x=1;
        }
        new B() {
            this.x=2;
        }
    }

I say "probably" because there's only a single declaration of `x` and it's at the class level not local to the constructor. Generating two local variables in the two constructors would work, but there's an argument that if the programmer didn't want `x` to be captured they should have just declared locally to the constructors.

Now in the next case — because of the constructor transformation we're using — we *have to* reify `x` as a field in order to "pass it" between `A` and `B`. However because it is only referenced during initialization using a field means (in the case of reference fields) memory leaks. (See also https://github.com/ceylon/ceylon-compiler/issues/1287 which is another instance of using fields unnecessarily, unrelated to constructors).

    class Captured {
        Integer x
        new A() {
            this.x=1;
        }
        new B() extends A() {
            print(x);
        }
    }

We could in *principle* nullify such fields at the end of the constructor.

We could try to figure out `Captured` correctly, but to be honest I think this is just a slippery slope of trying to get the compiler to figure out more and more complex and convoluted captures. 

Right now I'm very tempted to implement something simple but sometimes sub-optimal, but WDYT?

**Comment by gavinking** [comment]
> So similarly we probably wouldn't consider this captured: 

> ```ceylon
    class NotCaptured2 {
        Integer x;
        new A() {
            this.x=1;
        }
        new B() {
            this.x=2;
        }
    }
```

> I say "probably" because there's only a single declaration of `x` and it's at the class level not local to the constructor. Generating two local variables in the two constructors would work, but there's an argument that if the programmer didn't want `x` to be captured they should have just declared locally to the constructors.

I agree that we should not capture in this case.

> Now in the next case — because of the constructor transformation we're using — we *have to* reify `x` as a field in order to "pass it" between `A` and `B`. However because it is only referenced during initialization using a field means (in the case of reference fields) memory leaks
> We could in *principle* nullify such fields at the end of the constructor.

I would not bother with that, at least not in the first cut of this work.

**Comment by tombentley** [comment]
This was already fixed.

**Comment by gavinking** [comment]
OK, good.
