### ISSUE TITLE
constructor metamodel expressions for singleton constructors

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-compiler#2205]
I could have sworn that this was working an hour ago:

```ceylon
class Outer() {
    shared class Inner {
        shared String name => "Gavin";
        shared new instance {}
        shared new create() {}
    }
}

shared void run() {
    ValueDeclaration dec = `value Outer.Inner.instance`;
    ValueModel<Outer.Inner> ref = `Outer.Inner.instance`;
}
```

I get:

```
Method getConstructorDeclaration in interface ceylon.language.meta.declaration.ClassDeclaration cannot be applied to given types;
  required: java.lang.String
  found: com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor,java.lang.String
  reason: actual and formal argument lists differ in length
```

And then:

```
Compiler bug: visitor didnt yield any result at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.transformExpression(ExpressionTransformer.java:326)
```

**Comment by tombentley** [comment]
I don't get that. Is everything fully up to date?

**Comment by gavinking** [comment]
I just updated + rebuilt everything. Still happening.

**Comment by tombentley** [comment]
OK, I admit it. It was me that broke it. I thought I was fixing the metamodel constructor tests, because previously model literals of constructors were `Constructor` or `MemberConstructor`. I suppose they should now be `Function` (or `Method` for a member class) and `Value` (or `Attribute` for a member class).

For declarations can I say `new Class.ctor` and also `function Class.ctor` (or `value Class.singleton`)?

**Comment by gavinking** [comment]
Oh, um, not sure. Yeah, I guess that a value constructor should allow `new

**Comment by tombentley** [comment]
This should be fixed
