### ISSUE TITLE
Compilation error when having both an is-style and a get-style JavaBean property

### ISSUE THREAD

**Issue by davidfestal** [ceylon/ceylon-compiler#2222]
For example when the Java class being used has both `isNative()` and `getNative()` getters.

see ceylon/ceylon-ide-eclipse#1369 for more details

**Comment by FroMage** [comment]
Moving to 1.3, properly fixing this requires a lot of work.

**Comment by FroMage** [comment]
The suggested fix (do not create a value and keep both getters and the setter as methods) would break the inheritance chain if a supertype declares the getter/setter pair properly: we'd have a value for the supertype, and no implementation in the subtype. Or worse, make the three methods "implement" the value. I don't see any right way of doing this.

**Comment by FroMage** [comment]
What I may be able to do is set the ordering to always favour `is` or `get`.

**Comment by bjansen** [comment]
I’d favor `get`, chances are the `is` method will probably do a test on the value returned by `get`, so the calling code could emulate this test on the value returned by `get`.

**Comment by bjansen** [comment]
See `com.redhat.ceylon.model.typechecker.model.TypeDeclaration#getSelfType` and `com.redhat.ceylon.model.typechecker.model.TypeDeclaration#isSelfType` for an example.

**Comment by FroMage** [comment]
Well, what if you have `boolean isFoo()`, `String getFoo()` and `void setFoo(boolean b)`? Wouldn't you suppose that the getter is the wrong method?

**Comment by quintesse** [comment]
I would at least. As a general rule we could choose the one that is highest in the hierarchy (so if there's an `isFoo()` in a super-class and a `getFoo()` in a sub-class the is-version wins) and if they're all in the same class we could give preference to the one that has a matching setter. If there's no setter or the setter doesn't match we'd choose the `getFoo()`. All very arbitrary of course, but as long as one can at least predict the behaviour it should be okay.

**Comment by FroMage** [comment]
OK, so I rewrote the thing to be more correct and better defined. These are the new rules:

- JavaBean properties are collected first
- Any `toString()` method wins as an attribute over `getString`/`isString` (which would then be added as methods)
- Any `hashCode()` method wins as an attribute over `getHash`/`isHash` (which would then be added as methods)
- At this point, if we have more than one getter for a given name, one of them must be "is" and the other "get", as per JVM class file rules (since they both have no parameters we can't have more than one method with the same name, and there's only two valid names)
- If there is a single getter, we pick it
- If there are two getters and a single setter, we pick the getter that matches the setter
- If there are more than one setter, we ignore them entirely for selecting the best match
- If both getters return `boolean` we pick the "is" method (JB specs)
- Otherwise we pick the "get" method

Then, any setter that matches the getter we picked is used to make the property `variable`. Except `setHash` which is left as a method IFF we have `hashCode` AND `getHash`. Similar for `setString` with both `toString` AND `getString`.

Then we handle fields, unless there's a conflicting attribute (from JB properties).

Then we handle methods, and every non-picked getter/setter is added as a method.

This all fixes this issue, at the cost of more allocation and passes. It does not look at inheritance at all, because in most cases it can't (suppose conflicting definition in multiple interfaces) and it's expensive, which means that the model will be inconsistent wrt methods/attributes and overriding but that was already the case and nobody complained and it's really hard to fix.

**Comment by FroMage** [comment]
Done. Reopen if it doesn't work for you ;)
