### ISSUE TITLE
Reduce size of tuple type descriptor

### ISSUE THREAD

**Issue by vietj** [ceylon/ceylon-compiler#2228]
that can grow very large in some situations

**Comment by vietj** [comment]
for instance : https://gist.githubusercontent.com/vietj/8768fe6bf5b3d61652c5/raw/4ae563b2c64a2278b320ee6bcfbca51ec6a76685/gistfile1.txt

**Comment by gavinking** [comment]
I thought this had already been done in Ceylon 1.2?

**Comment by FroMage** [comment]
Not for `TypeDescriptor`, only for `@TypeInfo` signatures and `Tuple` instances.

**Comment by FroMage** [comment]
[Test comment, please ignore]

**Comment by FroMage** [comment]
So I'm getting there and have a special subtype of `TypeDescriptor.Class` called `TypeDescriptor.Tuple`, and I dynamically convert `TypeDescriptor.Class` of `Tuple.class` into it an also totally-optional tuples such as `[]|[X...]`, and it seems to pass my tests.

Now I have to think about the sort of tuples where we don't know the type of the rest element:

```ceylon
void shit<T,Element>() given T satisfies Element[] {
    test<Tuple<Integer|Element, Integer, T>>([1], [1, 2]);
}
```

I _think_ they don't exist at runtime because `T` will be known and has to be something that works with tuples.

**Comment by FroMage** [comment]
Aw fuck, I guess I can't represent fucked up tuples such as: `Tuple<Integer|String,Integer,[String,Integer]|[Integer,String]>` with this, or worse: `Tuple<Integer|String,Integer,[String,Integer]|[Integer,String]|[]>`.

Unless I special-case it even further to accept a `rest` part which is not conventional.

**Comment by FroMage** [comment]
This issue is getting ridiculously hard to fix.

**Comment by FroMage** [comment]
OK, I think I handled all the cases, including the crazy ones and my tests pass. Now I run the general tests and see 150 failures to check by hand (with luck it's just source difference/improvements).

This will have to wait for tomorrow morning. But perhaps I can merge this tomorrow.

**Comment by vietj** [comment]
sure, just let me know when I can give a try.

**Comment by FroMage** [comment]
I'm about half-way through manual checking :(

**Comment by FroMage** [comment]
Done!

**Comment by gavinking** [comment]
Hooray!

**Comment by vietj** [comment]
awesome dude, will let you know :-)

**Comment by quintesse** [comment]
Nice job!
