### ISSUE TITLE
generate transient modifiers on $init$whatever fields

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-compiler#2250]
For `late` attributes we sometimes generate a `$init$whatever` field. This is causing @sgalles headaches  when working with JPA. I recommend:

- we avoid generating this field when unnecessary, and use a `null` check instead, and
- we add the `transient` modifier to it when it actually _is_ really necessary.

**Comment by gavinking** [comment]
@tombentley?

**Comment by FroMage** [comment]
There are many cases where we don't know if `null` is a valid value, including optional types and unbounded generics. As for `transient` that's a bit of an abuse of its meaning because it would guarantee that using Java serialisation (like being part of an integration with a Java framework, perhaps even JPA providers would use it?) would fail.

In the case of JPA if you put your annotations on getters rather than fields, that problem would go away. What we _could_ do, is generate the variable with a `@Generated` annotation (though it's not clear to me that JPA respects it) or a `ACC_SYNTHETIC` flag in the bytecode (but again, not sure it respects that). I'll investigate.

**Comment by FroMage** [comment]
Pfff, JPA respects neither `@Generated` not `ACC_SYNTHETIC`, and only _barely_ implies that it will ignore values with the `transient` modifier. If I could get my hands on the amateur that produced this spec…

**Comment by FroMage** [comment]
OK, whatever. Done. We'll get to handle the `transient` issues when people complain. At least for now it should solve the issue for JPA users.
