### ISSUE TITLE
Runtime verify error when invoking a Java 8 static method interface

### ISSUE THREAD

**Issue by vietj** [ceylon/ceylon-compiler#2283]
Reproducer : https://dl.dropboxusercontent.com/u/4392533/ceylon_verify_error_static_interface_method.tgz

execute build.sh to reproduce

**Comment by FroMage** [comment]
So we generate the right bytecode. The problem is that we generate a classfile version 51 (Java 7), and the Java 8 verifier will reject that bytecode unless the classfile is version 52 (Java 8).

I suppose we can generate the 52 classfile version (unless the 51 format is invalid when passing as 52, I'd have to check) when running on Java 8 but that would essentially make all our generated .cars invalid on Java 7 when run on Java 8, which may not be what we want by default.

I can add a flag to make it explicit and still default to generating Java 7 class files, or I can detect any call to static interface methods and set the classfile to 52 (but that's probably very confusing behaviour). I can't rely on importing Java 8 modules to detect the version we want to generate as that can happen for any module import (in this case Vert.x).

**Comment by FroMage** [comment]
The Javac behaviour is to generate the classfile of its release by default and use flags to generate lower classfiles. By default we could do that too, and generate 1.7 classfiles, but allow a flag to generate higher version classfiles (1.8). It's not exactly the same, but it's sorta the same mindset…

**Comment by lucaswerkmeister** [comment]
Perhaps generate v52 when there’s an `import java.base "8"` module import? Use that as the explicit flag?

**Comment by FroMage** [comment]
Well no, as I explained that's not enough: I can import a Java 8 module that is not from the JDK, such as Vert.x, and still get the error.

**Comment by lucaswerkmeister** [comment]
Yes, and the solution would be that the user explicitly imports `java.base "8"` in addition to Vert.x.

Though come to think of it, that’s not very discoverable…

**Comment by tombentley** [comment]
> By default we could do that too, and generate 1.7 classfiles, but allow a flag to generate higher version classfiles (1.8). It's not exactly the same, but it's sorta the same mindset…

I think this is the right thing to do: Basically each release of our comiler has a default classfile version and if you want to deviate from that you have to be explicit with a compiler flag. I suppose that means we must reject invocations of interface statics when the target byte code version doesn't support it.

**Comment by vietj** [comment]
so actually this happens at the moment in the Ceylon module that implements the Ceylon Vert.x interface that calls the Vert.x jar . I think that somebody using this Ceylon module would not invoke directly static interface methods as this is done by the module he is using.

**Comment by FroMage** [comment]
OK fixed. Now you have to set `--javac=-target=8` and it will work.

As a nice side-effect we also get rid of the warning that class file format 52 is unsupported, because it should be fine, the extra attributes will be ignored and the new flags will work fine in theory.

I have made it a backend error to call static interface methods without that flag, even in Java.

**Comment by vietj** [comment]
thanks!

**Comment by vietj** [comment]
solved my problems, thanks again.
