### ISSUE TITLE
incompatible types taking ref to (x of MutableMap).defines

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-compiler#2289]
With:
```ceylon
    MutableMap<Object, Usable> mm = nothing;
    value defines1 = mm.defines; // Incompatible types
    value defines2 = (mm of Map<Object,Usable>).defines; // ok
    value defines3 = (mm of MapMutator<Object,Usable>).defines; // ok
```
we get:
```
Incompatible types
  required: ceylon.collection.MutableMap<java.lang.Object,ceylon.language.Usable>
  found:    ceylon.language.Map<capture#1 of ? extends java.lang.Object,capture#2 of ? extends ceylon.language.Usable> 
```

**Comment by tombentley** [comment]
This one's tricksy. The problem stems from the types in the tree. The QME has the one type but it's primary has the other. We use the one for the receiver variable for the method reference, but cast the initializing expression for that variable to the other.

It's not obvious which of the two types is really the best, since changing either causes problems elsewhere. And in the course of this I found a related problem with refs to a receiver of union type.
