### ISSUE TITLE
“error: cannot find symbol” when referring to class that has parameter list and default constructor

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-compiler#2290]
```ceylon
class C() {
    shared new() {}
}
C c = C();
```
In addition to the typechecker error

> error: class with parameters may not declare constructors: class 'C' has a parameter list and a constructor

you also get a backend error:

> error: cannot find symbol
```ceylon
C c = C();
       ^
```
  symbol:   class C
  location: package tmp

And, if you instead declare a class extending `C`
```ceylon
class D() extends C() {}
```
you also get

> error: method does not override or implement a method from a supertype

(without location info).

As always, [generated code](https://gist.github.com/lucaswerkmeister/37f29f5ccc777d29c085), `@noanno`’d; you can see that the “method [that] does not override or implement a method from a supertype” is the `$getType$()` method.

**Comment by jvasileff** [comment]
Is it advantageous to report backend errors when typechecker errors exist? I've often seen these, and have just tried to ignore them. One case I noticed just now:

<img width="515" alt="screen shot 2015-08-30 at 10 56 23 am" src="https://cloud.githubusercontent.com/assets/236050/9567831/898a799a-4f06-11e5-820f-2a9601609c46.png">

**Comment by tombentley** [comment]
@jvasileff we basically take the stance that there should *never* be backend errors (even if the code is littered with tc and syntax errors), so please report them as/when you see them.

**Comment by jvasileff** [comment]
@tombentley ok, thanks, I'll create an issue for that one.

But what I was wondering is if it makes sense to report these errors *to the user*, since it seems like a nearly impossible challenge for the compiler to always produce valid Java code from invalid Ceylon code. This is also interesting to me since even attempting to compile bad code isn't really possible for a backend that uses `ceylon.ast`, since `ceylon.ast` quite often disallows (throws for) invalid code. So I'm curious as to the benefits.

**Comment by lucaswerkmeister** [comment]
@jvasileff well, usually for invalid statements the compiler cancels the surrounding code block by adding a `throw new UnresolvedCompilationError("error message")` statement. This is probably what should also happen in this case (generate a class with a constructor that throws, instead of not generating a class at all).

And this is actually very useful. For example, `ceylon.ast` currently doesn’t *quite* compile due to #2179, but it doesn’t matter as much since the compiler still generates a .car file and I never actually call the method that throws the error. If the compiler just aborted completely, I wouldn’t have been able to work on `ceylon.ast` for the past couple of months.

And `ceylon.ast` only rejects *syntactically* invalid code. The code of this issue, for example, would still be accepted. And my general intention is that if anyone is going to write a compiler based on `ceylon.ast`, and they want to have a more lenient parser, they can attach additional info, for example:

```ceylon
// we have detected that there is a function definition, but a return type is missing
// we generate a fake return type that the compiler will later complain about
value retType = ValueModifier();
retType.set(isFakeKey, true);
value result = FunctionDefinition { … };
result.set(hasFakeReturnTypeKey, true);
```

**Comment by tombentley** [comment]
The code generator should always produce something that the javac backend can consume. In the presence of errors in the Ceylon source code there are a number of different things we can do:

* Produce nothing (this is usually what we do when a declaration has an error)
* Produce some alternative code (this is usually what we do when an expression has an error -- we generate code which will throw at the point the erroneous statement is reached)

You're right that there are limits do how far we can go with this: Obviously when we don't emit a declaration to javac because it's Ceylon declaration had an error then everything which depended on that declaration will be rejected by javac.

The main benefit of doing this for the user is they only see ceylon errors, rather than having to deal with a very confusing mix of ceylon errors mixed with javac errors (which are implicitly using a different type system).

The CLI compiler tries to figure out when javac has produced an error in order to print a message to make it plain that there's a bug in the compiler. Unfortunately it's not always possible to figure out reliably because of how javac handles it errors.

It's all quite dissatisfying, to be honest, but given the compiler architecture we have it's not clear how we could make it better.

**Comment by jvasileff** [comment]
@lucaswerkmeister Just add the `of` hint workaround :stuck_out_tongue_winking_eye:

**Comment by jvasileff** [comment]
Ok, thanks @lucaswerkmeister and @tombentley for the insight.

**Comment by tombentley** [comment]
For this particular case we could, I suppose, generate a "thrower constructor" for the default constructor (I mean the unnamed one, not the Java nullary default constructor). We would give it a `(Object...)` parameter list so that all callsites passed javac. If there's a sane way to arrange that...

**Comment by tombentley** [comment]
I've implemented this, though it's possible some edge cases make this error recovery itself go wrong.

**Comment by lucaswerkmeister** [comment]
Alright, thanks.
