### ISSUE TITLE
Annotations interop for java keywords

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-compiler#2325]
We should synthesize the following annotation classes

* `java.lang.\Itransient` (ReferenceDeclaration)
* `java.lang.\Ivolatile` (ReferenceDeclaration)
* `java.lang.\Istrictfp` (ReferenceDeclaration)
* `java.lang.\Isynchronized` (FunctionOrValueDeclaration)

Possibly we should also have `java.lang.\Istatic`, or a dedicated `serialVersionUid(1234)` class annotation

I'm not really sure if `java.lang.\Inative` makes sense -- the typechecker would need to know that a method with that annotation shouldn't have a body.

**Comment by tombentley** [comment]
Annoying dupe of #2324

**Comment by gavinking** [comment]
:-(

**Comment by gavinking** [comment]
Sorry.

**Comment by luolong** [comment]
> Possibly we should also have `java.lang.\Istatic`, or a dedicated `serialVersionUid(1234)` class annotation

If we are talking about those only in context of Java serialization, then maybe we can get by without those.

I mean, we can detect if we need to generate (synthetic?) `serialVerisonUid` field on the class (i.e. whenever it is deemed to be `Serializable`) and just generate it  based on the set of fields that are to be serialized.

After all, it _is_ required by the serialization on JVM.

The question is, what kind of a serialVersionUID generation strategy should we be using.

So far I've seen 3 ways people are doing this:
- Always zero (yes, this actually happens quite a lot)
- Increment by one every time an incompatible change is made
- Autogenerate a hash function of some sort each time an incompatible change is made

I have no idea which strategy should we pick, but I would say, allowing this to be set manually has almost always been abused in order to fix it to a specified value and forget it.

**Comment by tombentley** [comment]
> After all, it *is* required by the serialization on JVM.

Well the [javadocs](https://docs.oracle.com/javase/7/docs/api/java/io/Serializable.html) aren't quite that strong. It's merely *strongly recommended*, and defaults to some kind of [hash of the fields](https://docs.oracle.com/javase/7/docs/platform/serialization/spec/class.html#4100).

I don't think the compiler should go trying to do anything clever: We should let java serialization do it's default thing, or we should pass the buck to the user using whatever mechanism we decide.
