### ISSUE TITLE
ignore private constructor even when it is the only one

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-compiler#2327]
A bit minor, but when I have this Java class:

```java
class Foo {
    final String name;
    private Foo() {
        name = null;
    }
}
```

Then the model loader actually treats this as a class with a visible constructor. If I add a second, non-`private`, constructor, the problem goes away, and the model loader ignores the `private` one.

Now that we can have classes with no parameter list, I think we can just ignore a `private` constructor even when it is the only constructor of the class.

**Comment by tombentley** [comment]
Easily done, but the error message is slightly misleading. "Class cannot be instantiated: 'XXX' does not have a default constructor". In Java-land a default constructor doesn't mean the same thing as in Ceylon, so the user might misinterpret the problem as being about the presence/absence of a nullary constructor. The actual problem is that it doesn't have a visible constructor. Worse this bad error message sometimes masks the more useful "instantiates or refernces a sealed class in a different module: ..." which at least hints that the problem is about visibility.
