### ISSUE TITLE
Java 'Integer' is not assignable to Java 'Serializable'

### ISSUE THREAD

**Issue by jpragey** [ceylon/ceylon-compiler#2340]
Hi,
Compiling the following code:
```ceylon
import java.lang { Integer }
import java.io { Serializable }

shared void run() {
    Serializable s = Integer(0);
}
```
fails:
```
$ ceylon compile
source/org/bug1/run.ceylon:6: warning: declaration is never used: 's'
    Serializable s = Integer(0);
                 ^
source/org/bug1/run.ceylon:6: error: specified expression must be assignable to declared type of 's': 'Integer' is not assignable to 'Serializable'
    Serializable s = Integer(0);
                   ^
1 error
1 warning
Note: Created module org.bug1/1.0.0
ceylon compile: There was 1 error
```
Same PB with Long, Float, Double and Short.
I'm using Oracle java 8.

**Comment by tombentley** [comment]
I wonder how you found this, since it's not really useful assigning anything to `Serializable`, but thanks for reporting it all the same.

**Comment by FroMage** [comment]
Well, there's another issue is that I bet you can't do:

```ceylon
import java.io { Serializable }

class Foo() satisfies Serializable{}

Serializable f = Foo();
```

Because we make `Serializable` implementation invisible.

**Comment by tombentley** [comment]
That should work actually, though I suppose we need tests for it. The reason is that in that case the model loader should use the `@SatisfiedTypes` annotation, not the interfaces given in the class file. 

However, as you've observed the implicit, under-the-tc-radar nature of all this means that we can't assign a value whose Ceylon type implements `Serializable` at the JVM level to something declared to be `Serializable` because the TC will prevent it (since it doesn't know that the Ceylon class is Serializable). In practice that might not be a problem because people don't usually write APIs using Serializable, but I'm sure there are plenty of exceptions.
