### ISSUE TITLE
Java serialization for value constructors

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-compiler#2354]
We should support serialization of classes like this:

```ceylon
class FaultType of halt|ex|none {
    shared actual String string;
    shared new halt { string = "HALT"; }
    shared new ex { string = "EX"; }
    shared new none { string = "NONE"; }
}
```

By generating `readObject()` and whatever else is needed.

**Comment by tombentley** [comment]
According to the spec an `object` is just an abbreviated class with a value constructor, but it will have a completely different, and incompatible serial form to a class with a single value constructor. I wonder if that's a problem, @gavinking ? I suppose we could fix it, which would allow refactoring an `object` into a class + single value constructor in a serialization-compatible way, but it would be more fiddly.

**Comment by gavinking** [comment]
Completely different in what way?

**Comment by tombentley** [comment]
In the case of a top level `object` it is sufficient to have a `readResolve()` which returns the singleton value (it just returns the result of the `static` getter). In the case of a class with value constructors, when one of those singleton instances is serialized we use `writeReplace()` to return a proxy whose `readResolve()` will return the singleton instance (obtained via reflection, so we can write a single proxy class). So the effect is the same by the bytes are completely different.

**Comment by gavinking** [comment]
Well I mean these constructs aren't binary-compatible to clients either, so it seems OK to me, at least for now.

**Comment by tombentley** [comment]
> these constructs aren't binary-compatible to clients either

Well that's also a problem. It would be nice if we could make those compatible, so refactoring between the two was BC. I wonder how much compiler code we could eliminate if we did that. Still for another issue, I suppose.

**Comment by gavinking** [comment]
Right.

**Comment by tombentley** [comment]
Finally I seem to have something working. I was trying to use a `writeReplace()`/`readResolve()` pair for member classes with value constructors, where the outer class has both callable and value constructors. This seemed to run afoul of the cryptically worded **Note** [here](http://docs.oracle.com/javase/7/docs/platform/serialization/spec/input.html#5981), because the outer instance held a reference to the inner instance and the inner instance held an (implicit) reference to its outer, so we were getting a CCE before the `readResolve()` was ever called.

The solution is (or at least appears to be) to add the `transient` modifier to the fields used to hold the member class instance.

I suppose I'll need to do something similar for member `object`s.

**Comment by tombentley** [comment]
With a member `object` I need to make the field `transient` too, to avoid the same exception. But then my `readResolve()` can go wrong because it's just returning the result of the getter which because of the `transient` is just null. In other words there's a problem because member objects are not lazily allocated (member classes with value constructors are lazily allocated, which is why we didn't have a problem with those). 

Does anyone recall if there's a good reason why member `object`s are *not* lazily allocated?

**Comment by FroMage** [comment]
Other than the semantics? That makes sense for package members where initialisation order is undefined, but for members it's supposed to be in order and not lazy.

**Comment by tombentley** [comment]
Excellent point. I'm going to need some coffee to figure this one out then...

**Comment by tombentley** [comment]
Hang on. With the way that `object`s declarations have been retrospectively cast in terms of value constructors + getters they can be lazily evaluated, or at least that interpretation seems OK according to the spec. @gavinking, is that right?

**Comment by gavinking** [comment]
I don't see any reason why they can't be lazy. The spec is silent in the question of whether value constructors are lazy or eager.

**Comment by tombentley** [comment]
This should now work, meaning:

* `objects` that are class members should be serializable
* classes with value constructors which are class members should be serializable.
* Moreover, if the outer class is an anonymous class, or the outer instance was obtained via a value constructor, it should *still* work: the ceylon semantics of there being a single instance of the member class in this case should not be violated.

**Comment by gavinking** [comment]
Thanks Tom!
