### ISSUE TITLE
Incompatible types on tuple-like Nothing

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-compiler#2359]
For this unusual code:

```ceylon
String s = nothing of Tuple<Nothing, Nothing, Nothing>;
//Incompatible types
//    required: java.lang.String
//    found:    ceylon.language.Sequence<capture#1 of ? extends java.lang.Object>
```

Given that there isn't a reason for anyone to write down a `Tuple` that is `Nothing`, I'm not sure there is any reasonable code that would trigger this bug.

**Comment by tombentley** [comment]
@gavinking can you explain how this is well typed?

**Comment by FroMage** [comment]
Yeah, this sounds like a typechecker bug.

**Comment by gavinking** [comment]
Well `Tuple<Nothing, Nothing, Nothing>` is exactly `Nothing` now, so no, it's not a bug.

**Comment by gavinking** [comment]
§3.2.5 very last bullet point.

**Comment by tombentley** [comment]
Ah ha, thank you!

**Comment by tombentley** [comment]
Fixed by changing some `isNothing()` to `isExactlyNothing()`. There are still plenty of places in the codebase where we're calling `isNothing()` though, so we might yet see other errors of this sort. Maybe the code generator should just us `isExactlyNothing()` exclusively, but it's not really clear to me that that would always be the right thing either.
