### ISSUE TITLE
ceylon war requires explicit version number

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-compiler#2372]
ceylon war servlet.example

Does not work. It must be:

    ceylon war servlet.example/1.0.0

**Comment by tombentley** [comment]
To be consistent with the other tools it should accept a list of modules instead of a single one.

Also the documentation needs to make clear that it operates on compiled modules (`.cars`) and not sources (I assume).

**Comment by tombentley** [comment]
The reason the tool requires a version number is that it's not tied to a project directory. You can run `ceylon war` in any directory since it operates on `.car`s in any of the configured repositories. Thus there's not necessarily a `source` directory from which we can glean what the 'current' version is. We can't use the highest version number available because versions numbers are not comparable.

**Comment by gavinking** [comment]
Well OK, but that's not apparent to the user _at all_, not even from the help page. Indeed, the most common usage pattern is to run `ceyon war` in my project directory immediately after `ceylon compile`, and wonder why the two tools have different syntax.

**Comment by tombentley** [comment]
Documentation improved.
