### ISSUE TITLE
incompatible types on manufactured Callable, Tuple

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-compiler#2377]
Attempting to call `f()` in the example below fails if the "inserted" parameter is an erasable type. The purpose of the `alias` is to easily change out the type, it's not an essential part of the reproduction.

```ceylon
alias Other => Integer; // Inconvertible types
//alias Other => String; // Inconvertible types
//alias Other => Destroyable; // works

void foo<Arguments>(Arguments args, Other other)
        given Arguments satisfies [Annotated*] {

    value f = nothing of Callable<Anything, Tuple<Other|Annotated, Other, Arguments>>;

    f(other, *args);
    //Inconvertible types
    //  required: ceylon.language.Sequential
    //  found:    ceylon.language.Integer
}
```

**Comment by tombentley** [comment]
Interesting. Back in #1466 @FroMage added support for spread arguments like this, but specifically only for the `f(*args)` case. Apparently at that time `f(other,*args)` was forbidden. It now seems to be allowed. 

I can box up the arguments into a sequence easily enough, but we'll need to construct some runnable examples since this clearly hasn't been tested before.

**Comment by tombentley** [comment]
The code we generate works in a very simple test case, closing.

**Comment by jvasileff** [comment]
Cool, thanks. That fixes the cases I had.
