### ISSUE TITLE
Ceylon copy tool with `--all` does not copy docs.

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-compiler#2394]
Not sure why.

**Comment by FroMage** [comment]
Tested with the language module.

**Comment by tombentley** [comment]
The `ModuleCopycat` makes a single call (with all the suffixes in the given `ArtifactContext`) to `RepositoryManager.getArtifactResults(ArtifactContext)` to find the artifacts to copy. The result doesn't seem to contain a result of each suffix (or each suffix present in any of the repos that the `RepositoryManager` is presuming to manage). 

So I think the problem is with the `RepoManager`'s confusing logic for handling multiple suffixes, but it's impossible to say because the lack of documentation in the CMR means I've no idea what contract that method is providing.

For the time being I'm just calling `RepositoryManager.getArtifactResults(ArtifactContext)` once for each suffix.

**Comment by quintesse** [comment]
The problem with this fix is that the artifact can now come from any repository at all, making some kind mashup while they should all be coming from the same one.

**Comment by tombentley** [comment]
True, that's not ideal, but I've opened https://github.com/ceylon/ceylon-module-resolver/issues/130

**Comment by quintesse** [comment]
Ok thanks!

**Comment by quintesse** [comment]
If my assumption is correct you guys saw this problem because you were trying to copy the language module. This is part of the system repository which has the highest priority. It also doesn't contain documentation in a normal build! So the copy tool first encounters the module there and uses that as the source to copy from, so no docs are included.
This change pieces together artifacts from all available repositories, which although in *this* case gives the desired result is not something we should generally do.
So I'd like to revert this change because it's not correct and the previous behaviour worked.

**Comment by FroMage** [comment]
Only if you make the output include the artifacts being copied and where it copies them from. Otherwise that's just too mysterious. Actually I'd even add a flag `--from-fucking-any-repo-you-dumbass-now-move-it`

**Comment by FroMage** [comment]
Because originally I said `--all` and thought it would include it but it did not and I didn't know that.

**Comment by quintesse** [comment]
Well theoretically we shouldn't have repos with different artifacts in them and I think it would be even more confusing if someone copied from A to B and wound up with more artifacts than those that were available in A.

But I can definitely show paths in the output.

**Comment by FroMage** [comment]
> Well theoretically we shouldn't have repos with different artifacts in them

During dev that's rather common.

I'm not arguing against your single-source point, I'm just saying if it had told me which artifacts it copied I would have seen that the docs were missing, and if it had told me where it came from I would have understood why.

**Comment by tombentley** [comment]
Fine revert it.

But there's another problem, if the language module docs are not in the system repo, and that is:

```
$ ceylon browse ceylon.language/1.2
Unable to find index.html at /home/tom/ceylon/ceylon-dist/dist/repo/ceylon/language/1.2.0/module-doc/api/index.html
```

**Comment by tombentley** [comment]
So really we need the docs to be part of the standard build, right?

**Comment by quintesse** [comment]
>  if it had told me which artifacts it copied

`--verbose=files` does that actually, should I just turn that on always?

**Comment by quintesse** [comment]
> So really we need the docs to be part of the standard build, right?

We can certainly do that yes, it was just left out to make the standard build we do dozens of time each day somewhat faster (because honestly who read the docs? ;) )
The release build includes it of course.

**Comment by tombentley** [comment]
OK, thanks @quintesse. 

The fact that `ceylon copy` will use whichever configured repo it finds which contains one of the artifacts is confusing. While in theory the configured repos might be supposed to have the same artifacts I think we can safely assume there will be times that they don't.

Maybe we should have a more explicit `--in=<repo>` argument?

**Comment by quintesse** [comment]
`--in=xxx` being short for `--no-default-repositories --rep=xxx`?

**Comment by FroMage** [comment]
> --verbose=files does that actually, should I just turn that on always?

Almost, I expect this:

```
Module ceylon.language/1.2.0 (js,car,src,doc) [1/1] Ok
```

**Comment by FroMage** [comment]
Yeah, I don't think the repo lookup is confusing, that's what every other tool does too.

**Comment by quintesse** [comment]
> Almost, I expect this:

Uhm yes, can't you just be satisfied with that exists right now? ^^

Which is:

```
Module ceylon.language/1.2.0 [1/1]
    > ceylon.language-1.2.0.car [1/5] Ok
    > ceylon.language-1.2.0-model.js [2/5] Ok
    > ceylon.language-1.2.0.js [3/5] Ok
    > ceylon.language-1.2.0.src [4/5] Ok
    > module-doc [5/5] Ok
```

**Comment by FroMage** [comment]
No, it's too verbose to be the default.

**Comment by quintesse** [comment]
So I now have something like this:

    Module ceylon.language/1.2.0 [1/1] From:/home/ceylon/.ceylon/repo (car, model.js, js, src, module-doc) Ok

Isn't that getting too verbose?

**Comment by FroMage** [comment]
It is, you can remove the source I guess, as long as it's visible in verbose mode, which I should run if I see that it's missing docs. Also can we get rid of `model.js` and replace `module-doc` with `doc`? I'd like this to reflect the command-line flags `--doc`, and it's shorter.

**Comment by quintesse** [comment]
Well, those *are* the official artifact names, but sure.

And the js model *is* a different artifact, what if it's the model that is not being copied/missing? Doesn't seem like a good idea to me.

**Comment by FroMage** [comment]
In theory we cannot produce one without the other.
